build_cmd: make all
build_dir: /Users/dylanm/Projects/proftpd-1.3.5/
coverity_root: /Applications/cov-analysis-macosx-2021.9.0/
skip_build: False
verbose: True
project_name: proftpd-1.3.5_dylanm
project_version: mar-30-2022
codelocation_name: proftpd-1.3.5
bd_url: https://testing.blackduck.synopsys.com
api_token: YTRjMDBhNWQtYmM1YS00NGQxLTkzZjEtOWI3NDk5Mzg4NzdlOjRiN2VjYzk1LWMxZTAtNDJjNS05NDk2LTZhZjkwYTA3NzZjNA==
insecure: True